### ISSUE TITLE
Animation loses proper state

### ISSUE THREAD

**Issue by azakus** [PolymerElements/neon-animation#103]
_From @tjboAtVidao on September 16, 2015 20:0_

https://elements.polymer-project.org/elements/neon-animation?view=demo:demo/index.html&active=neon-animated-pages

If you spam click this enough, eventually the animation will lose state. It's not a massive problem but seems to get worse when you have other elements on your page... I think I can solve it in our project by a de-throttle or de-bounce, or if there was a function that was like "isAnimationStillRunning()?"... but I consider this a bug within Polymer.

_Copied from original issue: Polymer/polymer#2441_

**Comment by cdata** [comment]
Can you create a reduced test case and re-open? Thanks.

https://github.com/PolymerElements/neon-animation/blob/master/CONTRIBUTING.md#filing-issues
