### ISSUE TITLE
Make Neon Available via Bower

### ISSUE THREAD

**Issue by paranoid-android** [PolymerElements/neon-animation#109]
Hello,

I am attempting to integrate Neon into a project. I am currently using Polymer and the Iron Elements. I have been able to successfully integrate those items into my project through Bower. However, when I attempt to run:

```
bower install neon-animation --save
```

I get an error that says: "bower ENOTFOUND     Package neon-animation not found".

How do install Neon via Bower? I see that the package description [exists](https://github.com/PolymerElements/neon-animation/blob/master/bower.json). I'm not sure why its not being found.

Thanks

**Comment by MeTaNoV** [comment]
this should work:
`bower install PolymerElements/neon-animation --save`

**Comment by notwaldorf** [comment]
Yup, that's right. You need the org name as well.

**Comment by paranoid-android** [comment]
Ah. Thank you for clearing that up.
