### ISSUE TITLE
Passing in distributed content into <neon-animated-pages> breaks removal of .neon-animating class

### ISSUE THREAD

**Issue by zerodevx** [PolymerElements/neon-animation#11]
If we pass in `<content>` into `<neon-animated-pages>` page changing breaks after the first page change. For instance,

```html
<neon-animated-pages selected="0">
  <content></content>
</neon-animated-pages>
```

This is because the `.neon-animating` class is not properly removed from the two affected pages (old page and new page). The method responsible is the `_completeSelectedChanged` function.

```javascript
  _completeSelectedChanged: function(oldPage, selectedPage) {
    console.log("_completeSelectedChanged",oldPage,selectedPage);
    if (selectedPage) {
      selectedPage.classList.remove('neon-animating');
    }
    if (oldPage) {
      oldPage.classList.remove('neon-animating');
    }
    if (!selectedPage || !oldPage) { // the issue lies here
      var nodes = Polymer.dom(this).querySelectorAll('.neon-animating');
      for (var node, index = 0; node = nodes[index]; index++) {
        node.classList.remove('neon-animating');
      }
    }
    this.async(this.notifyResize);
  },
```

Since `<neon-animated-pages>` implements *IronSelectableBehavior*, we can use the in-built `items` array which contains the correct list of selectable nodes to remove the `.neon-animating` class from, perhaps like this:

```javascript
  if (!selectedPage || !oldPage) { // this might be better
    this.items.forEach(function (node) {
      node.classList.remove('neon-animating');
    });
  }
```

This fixes the mentioned issue; I'll add this commit into my [fork] (https://github.com/zerodevx/neon-animation/tree/fix-attr-for-selected) that fixes the *attr-for-selected* issue #8 together later for your reference.

Thanks

**Comment by morethanreal** [comment]
Fixed in 4037ccad7eff5934cef475fbbdf23adfa36e8e67.
