### ISSUE TITLE
`animateInitialSelection` property brakes `neon-animated-pages` with the new iron-selector 1.0.8

### ISSUE THREAD

**Issue by vguillou** [PolymerElements/neon-animation#112]
`animateInitialSelection` property brakes `neon-animated-pages` with the new iron-selector 1.0.8.

## Expected outcome

The first page is animated upon entry when the `animateInitialSelection` property is set to `true` on the `neon-animated-pages`.

## Actual outcome

The `neon-animated-pages` crashes :boom: and stays blank, no page can be displayed anymore :

    neon-animated-pages.html:122 Uncaught TypeError: Cannot read property 'getAnimationConfig' of undefined

## Steps to reproduce

- Change the version of iron-selector int `bower.json` (`"iron-selector": "PolymerElements/iron-selector#^1.0.8"`)
- Run `bower install`
- Pick a demo, add the `animate-initial-selection` attribute to the declared `<neon-animated-pages>`
- Run the demo and voilà.

## Full stacktrace

    Uncaught TypeError: Cannot read property 'getAnimationConfig' of undefinedPolymer._selectedChanged @ neon-animated-pages.html:122
    Polymer.Base.extend._complexObserverEffect @ polymer.html:1630
    Polymer.Bind._modelApi._effectEffects @ polymer.html:1461
    Polymer.Bind._modelApi._propertySetter @ polymer.html:1445
    Polymer.Bind._modelApi.__setProperty @ polymer.html:1454
    Polymer.Base._addFeature._applyConfig @ polymer.html:1997
    Polymer.Base._addFeature._afterClientsReady @ polymer.html:1991
    Polymer.Base._addFeature._ready @ polymer-mini.html:70
    Polymer.Base._addFeature._readyClients @ polymer-mini.html:78
    Polymer.Base._addFeature._ready @ polymer-mini.html:66
    Polymer.Base._addFeature._tryReady @ polymer-mini.html:56
    Polymer.Base._addFeature._initFeatures @ polymer.html:3497
    Polymer.render @ polymer.html:4688
    Polymer.attached @ polymer.html:4672
    Polymer.Base._addFeature._invokeBehavior @ polymer-micro.html:392
    Polymer.Base._addFeature._doBehavior @ polymer-micro.html:387
    (anonymous function) @ polymer-micro.html:196
    Polymer.RenderStatus.whenReady @ polymer-micro.html:110
    Polymer.Base.attachedCallback @ polymer-micro.html:194
    Polymer.Base._addFeature.attachedCallback @ polymer-mini.html:100
    Polymer.Base._addFeature._readySelf @ polymer-mini.html:88
    Polymer._ensureReady @ polymer.html:4630
    Polymer._markImportsReady @ polymer.html:4635
    (anonymous function) @ polymer.html:4625
    Polymer.RenderStatus._makeReady @ polymer-micro.html:118
    (anonymous function) @ polymer-micro.html:124
    (anonymous function) @ timeline.js:21

**Comment by BartKoppelmans** [comment]
I can confirm this issue. Have exactly the same problem.

**Comment by cdata** [comment]
Thanks for the detailed report. I will take a look.

**Comment by fooloomanzii** [comment]
I get the same bug in my previous issue https://github.com/PolymerElements/neon-animation/issues/83:

http://jsbin.com/jahoni/edit?html,console,output

if you leave out *animate-initial-selection* the animation runs:

http://jsbin.com/gudedo/edit?html,console,output

**Comment by ozasadnyy** [comment]
Any ideas how to make it working?

**Comment by MeinAccount** [comment]
Try downgrading `iron-selector` to `1.0.7`. (Add `"iron-selector": "PolymerElements/iron-selector#1.0.7"` as dependency in your `bower.json`.)

**Comment by ozasadnyy** [comment]
@MeinAccount yeah, it helps. Thanks!
