### ISSUE TITLE
Animation not working correctly with paper-dialog and neon-animated-pages

### ISSUE THREAD

**Issue by itboy87** [PolymerElements/neon-animation#117]
When neon-animations used with paper-dialog and if we click paper-dialog toggle button fast again and again after that dialog will close and if you try to open it again it will open and close again.
Even paper-dialog demo have this problem simple paper-dialog buttons work good but transition button have this problem and neon-animated-pages also have this problem if we switch pages fast and  then page's order will become incorrect.

**Comment by cdata** [comment]
Thanks for filing an issue. We need to see a reduced test case in order to verify that there is a problem. Please re-open the issue when you have a test case, and consult our [contribution guidelines](../blob/master/CONTRIBUTING.md) for more details on filing issues!
