### ISSUE TITLE
Slide Up animation seems buggy in paper-dialog

### ISSUE THREAD

**Issue by diegohaz** [PolymerElements/neon-animation#124]
If you use `slide-*-animation` at `entry-animation`, the dialog slides and instantly flashes to its original position after the animation.
```html
<paper-dialog entry-animation="slide-up-animation" exit-animation="fade-out-animation" opened>
</paper-dialog>
```

The only `slide-` animation that works is `slide-down-animation`.

The `slide-from-` animations work fine too, but there aren't `slide-from-top` or `slide-from-bottom`.

**Comment by diegohaz** [comment]
Well, I just found the #82, which may solve this problem. Are there any updates?

**Comment by notwaldorf** [comment]
#82 was merged, so I'm going to close this. Please re-open this issue if it still occurs, with a JSBin containing a set of reproducible steps. Check this element's CONTRIBUTING.md for an example.
