### ISSUE TITLE
Paper-dialog inside Neon-animated-pages few seconds after being shown

### ISSUE THREAD

**Issue by ziszo** [PolymerElements/neon-animation#128]
< neon-animated-pages >
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;< paper-dialog >

Dialog closes after a few seconds.
Is there any work-around for this issue like https://github.com/PolymerElements/iron-list/issues/110

**Comment by cdata** [comment]
Thanks for filing an issue. We need to see a reduced test case in order to verify that there is a problem. Please re-open the issue when you have a test case, and consult our [contribution guidelines](../blob/master/CONTRIBUTING.md) for more details on filing issues!
