### ISSUE TITLE
Issues after latest update (v.1.1.1)

### ISSUE THREAD

**Issue by manfield** [PolymerElements/neon-animation#147]
We're experiencing some issues on nested neon-animated-pages components since version 1.1.1.
We're using Ben Davies' Date Picker, inside a neon-animated-pages.

These are the issues we noticed:

- "neon-animated-page"'s content inside Date Picker's component is not shown (opacity: 0)
- every animation performed inside the Date Picker (fades), triggers the top neon-animated-pages component's animation (slide left)

**Comment by manfield** [comment]
Same of #146

**Comment by vguillou** [comment]
It should be fixed in v1.2.1.

**Comment by dstockwell** [comment]
Fixed by https://github.com/PolymerElements/neon-animation/pull/169
