### ISSUE TITLE
NeonPages are catching every iron-selected-event inside a page

### ISSUE THREAD

**Issue by fooloomanzii** [PolymerElements/neon-animation#151]
in [2407334](https://github.com/PolymerElements/neon-animation/commit/240733416d882b87aeec1871a97aa438302e17e1) was added:

```
findSharedElements: function(config) {
  var fromPage = config.fromPage;
  var toPage = config.toPage;
  if (!fromPage || !toPage) {
    console.warn(this.is + ':', !fromPage ? 'fromPage' : 'toPage', 'is undefined!');
    return null;
  };
  ...
}
```

It was possible before to configure one element with an attribute for fromPage and and another with toPage. This doesn't seem to be possible anymore. There are animations, like hero-animations on pages, where you can not define within the element, which page came before or where it is going to.

Now the console is printing out:

> hero-animation: toPage is undefined!    neon-shared-element-animation-behavior.html:40

Somehow the variables aren't merged properly anymore.

**Comment by fooloomanzii** [comment]
But it might has something to do with an **iron-selector** inside a page

**Comment by bpinney** [comment]
This may be related to issues #146 and #147 as they are also affected by the iron-select listener.  There is a [great workaround](https://github.com/PolymerElements/neon-animation/issues/146#issuecomment-194622443) involving stopping propagation that worked for me, but pull request #149 may be the change you want.

**Comment by fooloomanzii** [comment]
It has something to with, that neon-animated-pages catches **every ** iron-select-event now

```
'iron-select': '_onIronSelect'`
```
and doesn't differ if its selection is a page or not

**Comment by reinert** [comment]
It's happening with me too.

**Comment by timeu** [comment]
same problem here. In fact with nested pags it acuses them to not render at all.

**Comment by JaySunSyn** [comment]
Same here. The selection of a paper-dropdown-menu triggers a page animation.

**Comment by cacerrillos** [comment]
Going to join the band with a "Same here".

Will try the event propagation workaround :/

**Comment by kungufli** [comment]
+1 same problem here

**Comment by TomasAgoston** [comment]
I would describe my particular problem as following:
- an unrelated IronSelect event withing the page is triggered on transition
- _onIronSelect gets called twice (once for the transtion, and once with the unrelated event)
- the opaque-animation is applied incorrectly on the page (does not display)

Probably also related to this:

https://groups.google.com/forum/#!topic/polymer-dev/iQ30oeTweyY

I would suggest to add the assumption check, that the page must be a direct child of neon-animated-pages:

```
    _onIronSelect: function (event) {
    	
      var selectedPage = event.detail.item;
      if (!selectedPage) return;

      var parent = Polymer.dom(selectedPage).parentNode
      if (parent != this) return;
...
}
```

I.e. validating the event.detail.item to be a 'page' of the neon-animated-pages.

**Comment by TomasAgoston** [comment]
Already suggested also here 8 hours ago:

https://github.com/PolymerElements/neon-animation/pull/161

**Comment by fooloomanzii** [comment]
treated here #149

**Comment by vguillou** [comment]
It should be fixed in v1.2.1.

**Comment by kungufli** [comment]
It seems fixed for me too.

**Comment by dstockwell** [comment]
Fixed by https://github.com/PolymerElements/neon-animation/pull/169
