### ISSUE TITLE
neon-animated-pages 1.1.1 wrong behavior

### ISSUE THREAD

**Issue by userquin** [PolymerElements/neon-animation#153]
Changes in version 1.1.1 to listen iron-select event: if including inside neon-animatable any component that fires iron-select event, neon-animated-pages applies entry and exit transitions to selected neon-animatable.

For example, including a paper-radio-group, clicking any paper-radio-button makes page appear and disapear when entry and exit transitions are fade-in and fade-out respectivelly.

**Comment by fooloomanzii** [comment]
#149

**Comment by samuelli** [comment]
Looks like a dupe of #146
