### ISSUE TITLE
Nested neon-animated-pages and complex animation sometimes causes exception

### ISSUE THREAD

**Issue by timeu** [PolymerElements/neon-animation#159]
### Description

I have two nested `neon-animated-pages` where the root one delegates on exit and entry to the child one:

```
animationConfig: {
                value: function() {
                   return {
                       'entry': [
                        {animatable: this.$.subpage1, type: 'entry2'},
                        {animatable: this.$.subpage2, type: 'entry2'}
                    ],
                    'exit': [
                        {animatable: this.$.subpage1, type: 'exit2'},
                        {animatable: this.$.subpage2, type: 'exit2'},
                    ]
                   }  
                },
            },
```

### Expected outcome

Should work without problems. 

### Actual outcome

After a specific sequence of page changes (reproducible) I get following error: 

```
Uncaught NotSupportedError: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
```
Interestingly the error is not thrown when I put a debug in neon-animation-runner-behavior.html for example and simply continue the execution. So to me it seems like a timing issue or race condition. 

### Demo:

Unfortunately I don't have a demo but I attache a screenshot of the Chrome Dev Tools. Maybe somebody can give me pointers where to look (it seems that there are 2 valid keyframes). 

This is with neon-animation 1.1.0 (can't upgrade to 1.1.0) because of #151 and webanimationjs (2.1.3)

![image](https://cloud.githubusercontent.com/assets/374296/14177480/bd1c2332-f756-11e5-8d6a-f886f6a52abb.png)

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by The5heepDev** [comment]
I have the same bug, except I have `neon-animated-pages` nested within `iron-pages`.

**Comment by timeu** [comment]
@The5heepDev 
Unfortunately this does not help in my case. It seem to happen if I change the parent page but have no animation entry for the sub page.

**Comment by dstockwell** [comment]
They keyframes appear to be invalid. I can see `scale(Infinity...` in the screenshot. But "Infinity" is not a valid value for scale.

**Comment by dstockwell** [comment]
Are you using a custom animation, or one provide by neon-animations?

**Comment by timeu** [comment]
@dstockwell:  I use custom animations (cascade and scaleup and sometimes hero)
I think I know what the reason might be for that error. 
The problem seems to be that in the parent page that contains the child `neon-animated-pages`, I delegated the animation to  both, `subPage1`  and `subPage2`. 
However only one of them is visible at a time and as a result one of the keyframes becomes `scale(Infinity...` because the dimensions of the elements in the hidden subPage can't be computed (at least that's my guess). 
I probably need to dynamically change the `animatable` property of the `animationConfig` based on which subpage is visible. 
For that I am now looking into [neon-page-behavior](https://github.com/vguillou/neon-page-behavior) that allows me to hook into the life cycle of the animations and customize it. 

However it would be handy if `neon-animation` could just ignore the `partial keyframes` errors or just animated those pages that are also visible.

**Comment by dstockwell** [comment]
After https://github.com/PolymerElements/neon-animation/pull/177 this failure will now only log a warning to the console.
