### ISSUE TITLE
Error: Failed to execute 'animate' on 'Element': 'function (a){return a}' is not a valid value for easing

### ISSUE THREAD

**Issue by alancutter** [PolymerElements/neon-animation#162]
### Description
Getting console error when using neon-animations with a build of Chrome that throws TypeErrors on invalid timing functions.
`Error: Failed to execute 'animate' on 'Element': 'function (a){return a}' is not a valid value for easing`
This is due to a bug in the web-animations-js polyfill that has been fixed in v2.2.0.

### Expected outcome
Repo tests should pass.

### Actual outcome
Most fail with the above error.

### Live Demo
Needs a custom build of Chrome with https://codereview.chromium.org/1851003002 patched in.

### Steps to reproduce
1. Build Chrome with https://codereview.chromium.org/1851003002.
2. Run neon-animation tests.

### Browsers Affected

- [ ] Chrome
- [ x ] Future Chrome
- [ ] Firefox
- [ x ] Firefox Nightly
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by fearphage** [comment]
FYI, this error also affects Opera v41 (developer build).
