### ISSUE TITLE
update web-animations-js to 2.2

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/neon-animation#167]
`bower.json` specifies an outdated version of `web-animations-js`: `web-animations/web-animations-js#2.1.4`

This version [has a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=601672) which triggers a warning in Blink:

> Specifying animation easing as a function is deprecated and all support will be removed in M54, around October 2016, at which point this will throw a TypeError. This warning may have been triggered by the Web Animations or Polymer polyfills. See http://crbug.com/601672 for details.

Also the new version probably has other goodness.

**Comment by ebidel** [comment]
Due to changes in canary, the old version has started to break sites. Updating fixes it. For example, the io 2015 site has stopped working in Chrome 52: https://events.google.com/io2015/

Who oversees this element ? cc @cdata @notwaldorf @valdrinkoshi

**Comment by samuelli** [comment]
Fixed in https://github.com/PolymerElements/neon-animation/pull/163
v1.2.1 includes this.

@ebidel: @dstockwell typically looks after this element, but he's away at the moment.
