### ISSUE TITLE
If required webanimation polyfills are missing, allow the element using neon-animation to still work.

### ISSUE THREAD

**Issue by helenxywu** [PolymerElements/neon-animation#174]
### Description
If the webanimation polyfills are not available, the element using neon-animation should still function (skipping the animation). 

### Expected outcome

Elements using neon-animation should not break when webanimations polyfill are missing. Instead they should skip the animation.

### Actual outcome

Elements using neon-animation without the polyfill stop working. An error occurs and the animation doesn't finish. For example, dropdowns have a fade in animation going from 0 to 1 opacity. The opacity stays at 0 because the animation never finishes.

**Comment by dstockwell** [comment]
I think this makes a lot of sense. We'll likely achieve this by having calls to `AnimationBehavior`'s `configure` function turn exceptions into warnings. We'll also need to fire the finish events immediately.
