### ISSUE TITLE
neon-animated-pages reverse animation?

### ISSUE THREAD

**Issue by firasdib** [PolymerElements/neon-animation#20]
Hello,

I'm using neon-animated-pages which is working fine, but the trouble is "reversing" the animation when the user navigates backwards in the UI.

So imagine this:

````
<neon-animated-pages id="pages" class="flex fit" selected="[[selectedPage]]">
  <a-page>...</a-page>
  <a-page>...</a-page>
</neon-animated-pages>
````

The initial value of `selectedPage` is `0` which is fine, the first page is shown. The user presses a button on this page and `selectedPage` is now `1`. In my case, `slide-from-right-animation` is run and the pages move "forward" as you would expect. The user now presses an internal back button and the `selectedPage` variable is changed from `1` to `0` -- moving backwards. The same animation is still run however, making it look like the page is moving forward although its in reality moving backwards.

I hope this makes sense, if not, I'll clarify.

Is there a way to make the animation reverse when you move backwards, i.e., running `slide-from-left-animation` instead?

Thanks

**Comment by morethanreal** [comment]
You can achieve that effect by defining a different animation for the entry and exit. When the page transitions from `0` to `1`, `0`'s exit and `1`'s entry is run and when it transitions from `1` to `0` `1`'s exit and `0`'s entry is run. For `1` to slide back and forth from the right, you could define its entry to `slide-from-right-animation` and its exit to `slide-right-animation`.

**Comment by firasdib** [comment]
@morethanreal Yes, I would define the same exit and entry animation for both. I am however trying to keep this to one element, so `<a-page>` is used for all pages -- I was hoping for some sort of automatic way of switching the animation from `slide-right-animation` to `slide-left-animation`. I tried capturing the event that is fired after the animation is finished to switch it, but it does not reach my element -- it's picked up and retained by the parent. 

Does this clarify my issue or did I misunderstand you?

**Comment by morethanreal** [comment]
Did you want both pages to animate, or just the incoming page to animate? You should be able to set `animationConfig` before running the transition. For example to animate both pages, in the element containing `neon-animated-pages`:

```
switchPage: function() {
  var from = this.selectedPage;
  var to = this.selectedPage === 0 ? 1 : 0;
  this.$.pages.items()[from].animationConfig = {
    'entry': {
      name: 'slide-left-animation'
    }
  };
  this.$.pages.items()[to].animationConfig = {
    'entry': {
      name: 'slide-from-right-animation'
    }
  };
  this.selectedPage = to;
}
```

This is similar to `demo/declarative/index.html` in the repository.

> I tried capturing the event that is fired after the animation is finished to switch it, but it does not reach my element -- it's picked up and retained by the parent.

I'm not sure I understand this---could you clarify this issue?

**Comment by firasdib** [comment]
I ended up extending neon-pages into my own element which does what I want. 

I need to define 4 animations, used in pair, depending on which direction you move. If you move forward, the pages use `slide-from-right-animation` and `slide-left-animation`. If you move backwards, you use `slide-from-left-animation` and `slide-right-animation`. 

I can paste some code tomorrow if you want to see in more detail.

**Comment by morethanreal** [comment]
It appears there is no action item from this issue. Please re-open if you believe this is in error.
