### ISSUE TITLE
Cannot assign to read only property 'target' of object '#<AnimationPlaybackEvent>'

### ISSUE THREAD

**Issue by govis** [PolymerElements/neon-animation#229]
### Description
All Demos yield a <code>Cannot assign to read only property 'target' of object '#&lt;AnimationPlaybackEvent>'</code> error coming from https://github.com/web-animations/web-animations-js/blob/master/src/web-animations-next-animation.js#L223

neon-animation v2.0.0 (2.0-preview)
web-animations-js v2.2.3
polymer v2.0.0-rc.4
webcomponentsjs v1.0.0-rc.8

### Expected outcome
No errors

### Actual outcome
Cannot assign to read only property 'target' of object '#<AnimationPlaybackEvent>'" error 

### Live Demo
Run any of the demos:

![image](https://cloud.githubusercontent.com/assets/971651/25009633/4e3bed54-2035-11e7-8439-8ece1a1026d1.png)

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by govis** [comment]
Looks like it has something to do with the 2.2.3 commit in web-animations/web-animations-js: https://github.com/web-animations/web-animations-js/issues/123

**Comment by krumware** [comment]
Getting the same issue over here. neon-animation references web-animations-js version 2.2.0, but version 2.2.3 is the actual version being pulled. 2.2.0 is not an available release tag in web-animations-js https://github.com/web-animations/web-animations-js/releases

**Comment by krumware** [comment]
Also, I wanted to clarify, the issue here references Polymer 2.0+, but we are seeing the same issue on Polymer 1.8.1

**Comment by krumware** [comment]
our temporary fix was to add the following to bower.json
`"web-animations-js": "web-animations/web-animations-js#2.2.2"`

**Comment by fungusamongus** [comment]
We also had this problem in one of our polymer projects and fixed it by setting the specific 2.2.2 tag in our bower. This is with Polymer 1.8.1

**Comment by samuelli** [comment]
Just to keep everyone in the loop. I'm trying to get this fixed upstream in web-animations. If that doesn't resolve in the next few hours, we'll go with this stop-gap solution in #230

**Comment by krumware** [comment]
Thanks Sam!

**Comment by samuelli** [comment]
Thanks for your patience. This has been fixed upstream in https://github.com/web-animations/web-animations-js/pull/124. Please update to v2.2.4 for web-animations-js and the issue should be resolved.
