### ISSUE TITLE
web-animation-js not found in production after last release!

### ISSUE THREAD

**Issue by AliMD** [PolymerElements/neon-animation#245]
### Description

We use polymer in production and all our products broken in new bower install!

![screen shot 2018-02-21 at 9 54 15 am](https://user-images.githubusercontent.com/697913/36466063-7056567c-16ed-11e8-95d8-18e68d250d00.png)

The new updates of `neon-animation` had some modifications in the bower.json, and `web-animation-js` is moved in devDependencies instead of dependencies so bower doesn't download/unpack it if the right flash isn't set.

Would it not be more logical to put it back in dependencies?

Thank you in advance.

**Comment by AliMD** [comment]
I'm confusing I check All v2 version and have the same issue!
When we import `neon-animation/web-animations.html` it must have the dependencies!

**Comment by merlinnot** [comment]
1) This element is deprecated 
2) You’re supposed to import a polyfill yourself, as you do with any other polyfills (web components, reflect, whatever)

It’s a pretty easy fix :)

**Comment by AliMD** [comment]
I import it but it does not install with bower anymore ?!
I'm confusing why its change in my last release with any code changes!
