### ISSUE TITLE
Changing transition animations on the fly

### ISSUE THREAD

**Issue by agozie** [PolymerElements/neon-animation#25]
Changing the exit animation of neon-animated-pages by modifying animationConfig object did not work for me. I tried to switch from 'scale-down-animation' to hero animation dynamically, but it did not work.

**Comment by cedric-marcone** [comment]
I didn't have this need but animationConfig declared as a computed property should work for you.

**Comment by agozie** [comment]
I declared animationConfig as a computed property but still not working. I have 3 pages. From first to second, hero and ripple works fine. From first to third, it works.But from second to third, it hangs in Firefox and Safari, shows now animation in chrome.

**Comment by morethanreal** [comment]
@agozie Can you give some example code (codepen or jsbin would be best) of the broken case?

**Comment by cedric-marcone** [comment]
As I previously commented, computed properties work fine. I just had to implement this use case and it worked like a charm : 
```js
properties: {

    back: {
      type: Boolean,
      value: true
    },

    animationConfig: {
      type: Object,
      computed: '_computeAnimation(back)'
    }
  },

  _computeAnimation: function(back) {
    const entryWay = back ? 'left' : 'right'
    const exitWay = back ? 'right' : 'left'
    return {
      'entry': [{
        name: `slide-from-${entryWay}-animation`,
        node: this
      }],
      'exit': [{
        name: `slide-${exitWay}-animation`,
        node: this
      }]
    }
  }
```

**Comment by morethanreal** [comment]
Ok, closing this issue since there seems to be no action for this element. Please re-open if you believe this is in error.
