### ISSUE TITLE
neon-animation-finish is not triggered with shared animations.

### ISSUE THREAD

**Issue by hourliert** [PolymerElements/neon-animation#28]
Hi,
It seems the `neon-animation-finish` event is not triggered when using the ripple shared animation.
Both the incoming or outgoing pages can't listen on this event.

I want to 'reset' the shared Elements after the end of the ripple animation but I can't find out how without event.

Thanks in advance.

**Comment by naoak** [comment]
`neon-animation-finish` event fires without bubbling up on `neon-animation-runner-behavior` element such as `neon-animated-pages`. So I think you should directly listen on the `neon-animation-runner-behavior` element.

**Comment by zmoshansky** [comment]
The following worked for a custom element contained in a `neon-animated-pages` set. YMMV.
```
attached: function() {
        this.async(function() {
          document.querySelector('#main-pages-container').addEventListener('neon-animation-finish', function() {
              console.log('animation finished');
          });
        });
      },
```

**Comment by hourliert** [comment]
Thanks you for your answer. It works. I wanted to listen on the event into the `NeonSharedElementAnimatable` but it doesn't matter. The parent element could notify them after receiving this event.

**Comment by notwaldorf** [comment]
Does this work ok now? Can I close the issue? :)

**Comment by hourliert** [comment]
Yes, thank you. :)
