### ISSUE TITLE
Recent Blink changes break <neon-animated-pages>

### ISSUE THREAD

**Issue by dzhioev** [PolymerElements/neon-animation#32]
I've noticed that [recent changes in Blink] (https://code.google.com/p/chromium/issues/detail?id=496527#c4) break `<neon-animated-pages>` in some cases.

Here is an small example, where the issue appears -- http://dzhioev.net:8080/animation_pages.html -- selected page is set to '1', but shortly after (before the transition is finished) selected page is set to '0'.

In the latest dev Chromium (which includes the noted Blink change), `<neon-animated-pages>` remains in inconsistent state after all transitions are finished: both pages have `.neon-animating` class set, which make them non-interactive (as `.neon-animating` implies `pointer-events: none`).
![Dev Tools Screenshot] (http://dzhioev.net:8080/pages.png)
This happens because `<neon-animated-pages>` is set up to skip the first finish animation event after animation cancellation (`_squelchNextFinishEvent`), assuming that this event belongs to the cancelled animation.

**Comment by morethanreal** [comment]
Need to check if the web animations polyfill matches the new behavior in Chrome and fix the code/file bug as needed.

**Comment by morethanreal** [comment]
Looks like there's an issue opened in the web animations polyfill to make the behavior match: https://github.com/web-animations/web-animations-next/issues/368. Waiting for that one to land.

**Comment by cdata** [comment]
I think this change has landed in the polyfill. We should update the polyfill.

**Comment by dstockwell** [comment]
This was fixed in web-animations-js and the dependency in neon-animations had been updated.
