### ISSUE TITLE
Fires an event with undefined type

### ISSUE THREAD

**Issue by jklein24** [PolymerElements/neon-animation#34]
https://github.com/PolymerElements/neon-animation/blob/master/neon-animation-behavior.html#L83

I don't see where this.animationEndEvent is defined anywhere. Am I missing something?

**Comment by morethanreal** [comment]
That's a bug from when animations are independently runnable and the code should probably be removed.

**Comment by jklein24** [comment]
Fixed by https://github.com/PolymerElements/neon-animation/pull/33
