### ISSUE TITLE
Clarification on when to insert "opaque-animation"

### ISSUE THREAD

**Issue by zerodevx** [PolymerElements/neon-animation#36]
@morethanreal referring to https://github.com/PolymerElements/neon-animation/blob/master/neon-animatable-behavior.html#L53, 

```js
   _entryAnimationChanged: function() {
      this.animationConfig = this.animationConfig || {};
      if (this.entryAnimation !== 'fade-in-animation') {
        // insert polyfill hack
        this.animationConfig['entry'] = [{
          name: 'opaque-animation',
          node: this
        }, {
          name: this.entryAnimation,
          node: this
        }];
      } else {
        this.animationConfig['entry'] = [{
          name: this.entryAnimation,
          node: this
        }];
      }
    },
```

shouldn't the polyfill hack be inserted *only* if `this.animationConfig === "fade-in-animation"`?

**Comment by morethanreal** [comment]
`opaque-animation` works around an issue when using the WA polyfill where a frame is drawn between making the incoming page `display:block` and the animation starting by making it `opacity:0` until the animation starts, so it's needed for all animations.
