### ISSUE TITLE
Example using cascaded-animation with dom-repeat

### ISSUE THREAD

**Issue by techniq** [PolymerElements/neon-animation#37]
I've been struggling to find an example of using cascaded-animation with dynamic content (`dom-repeat`).  In the below snippet, `{{ images }}` is asynchronously set from an API call.  Is it possible to wait / perform a cascaded animation once the images are loaded?  I know `Polymer.dom(this).querySelectorAll('.image')` returns an empty result since `dom-repeat` has not created the elements when that line executes.

```html
<template>
  <template is="dom-repeat" items="{{images}}">
    <div class="image" style$="{{ _computeStyle(item.data) }}">
      <div class="title">{{ item.data.title }}</div>
    </div>
  </template>
</template>

<script>
    Polymer({
      is: 'image-list',
      properties: {
        images: Array,
    
        animationConfig: {
          type: Object,
          value: function() {
            return {
              'enter': [{
                name: 'cascaded-animation',
                animation: 'transform-animation',
                transformFrom: 'translateY(100%)',
                nodes: Polymer.dom(this).querySelectorAll('.image')
              }]
            }
          }
        }
     ...
    }
</script>
```

**Comment by morethanreal** [comment]
You can set the `animationConfig` property in code after the template is stamped, and before calling `playAnimation`, or before switching pages if you're using `neon-animated-pages`.

ie.
```html
<neon-animated-pages id="animatedPagesInstance">
  <image-list id="imageListInstance"></image-list>
  <other-page></other-page>
</neon-animated-pages>
```
```js
this.$.imageListInstance.animationConfig = /* your config */
this.$.animatedPagesInstance.selected = 0;
```

**Comment by techniq** [comment]
@morethanreal perfect, thanks.

**Comment by techniq** [comment]
@morethanreal Any chance you could put in your backlog to show an example of how to do this.  I spent some time last night trying to do this on load with some async data (from a rest call) and couldn't get the timing right.  


I tried to listen to the `dom-change` event of `dom-repeat` and play the `entry` animiation manually but I couldn't get it to work.  Here is the snippet I was trying:
```html
<dom-module id="image-list">
  <style>
    ...
  </style>
  
  <template>
    <template id="images" is="dom-repeat" items="{{images}}">
      <div class="image" style$="{{ _computeStyle(item.data) }}">
        <div class="title">{{ item.data.title }}</div>
      </div>
    </template>
  </template>

  <script>
    Polymer({
      is: 'image-list',
      behaviors: [
        Polymer.NeonSharedElementAnimatableBehavior,
        Polymer.NeonAnimationRunnerBehavior
      ],
      attached: function() {
        this.$$('#images').addEventListener('dom-change', function(e) {
          var element = e.srcElement.parentElement;
          var nodeList = element.querySelectorAll('.image');
          element.animationConfig['enter'][0].nodes = Array.prototype.slice.call(nodeList);
          element.playAnimation('entry');
        });
      },
      properties: {
        images: {
          type: Array,
        },
        animationConfig: {
          type: Object,
          value: function() {
            return {
              'enter': [{
                name: 'cascaded-animation',
                animation: 'transform-animation',
                transformFrom: 'translateY(100%)',
                transformTo: 'none',
                timing: {
                  delay: 50
                }
              }]
            }
          }
        }
      }
    });
  </script>
</dom-module>
```

This is a snippet from my [codepen](http://codepen.io/techniq/pen/QbgXKY) but the code is very ugly and just me trying to learn Polymer / neonanimations so you might not want to look at it ;)

**Comment by morethanreal** [comment]
@techniq I checked out your codepen, and the animations looks to be working. Do you still want an example?

**Comment by techniq** [comment]
@morethanreal  I was able to get the hero transition working to go from the 'list' view to the image 'preview', but couldn't find a way to perform an animation when the 'list' view pulled in the images.

I'd like to be able

1. Perform a `iron-ajax` request for a list of images
2. Stagger layout the images 

It would be similar to animation on load [example](http://morethanreal.github.io/neon-animation-demo/bower_components/neon-animation/demo/load/index.html) / [code](https://github.com/PolymerElements/neon-animation/tree/master/demo/load), but after a core-ajax response instead of on initial page load.  I'm not sure how playing the animation works with the `<template is="dom-repeat">`

**Comment by cdata** [comment]
@techniq I'm not sure that any single animation is a good solution for animating individual staggered items. I would recommend animating each loaded item individually as an alternative design.
