### ISSUE TITLE
Outline is shown when clicking on any element on the page when animation comes in.

### ISSUE THREAD

**Issue by motss** [PolymerElements/neon-animation#39]
Border-outline will appear when clicking on any element when animation is being applied on **neon-animated-pages** especially with **neon-animatable**. However, this can be overcome by applying some CSS styling to disable all nasty outline:
```
*:focus {
    outline: none;
}
```

**Comment by morethanreal** [comment]
Do you mean you're clicking on an element that's being animated?

**Comment by motss** [comment]
Sorry for the late response. I tried to reproduce the error but I failed to do so because for unknown reason it seemed working without showing any outline even with the *:focus removed from the CSS styling. My code basically looked like this:
````
<!-- animated-page -->
<neon-animated-pages selected={{selected}} 
                     entry-animation="slide-from-right-animation" 
                     exit-animation="slide-left-animation">
    <neon-animatable>
        <my-custom-element></my-custom-element>
    </neon-animatable>

    <neon-animatable>
        <my-element></my-element>
    </neon-animatable>
</neon-animated-pages>

<!-- button using paper-material -->
<paper-material on-tap="_nextPage">Next Page</paper-material>
````

**Comment by morethanreal** [comment]
Since it seems to be working, I'm closing this issue. Please re-open with an example that reproduces the issue if you believe this is in error!
