### ISSUE TITLE
Animated pages overlapped each other.

### ISSUE THREAD

**Issue by motss** [PolymerElements/neon-animation#46]
The pages overlapped as seen in the image. 

![Page 1 and Page 2 overlapped](https://cloud.githubusercontent.com/assets/10607759/8445373/d554d6ac-1fce-11e5-9091-8b67db95efb6.png)

**Comment by morethanreal** [comment]
@motss The image is broken for me. How do you reproduce the issue?

**Comment by motss** [comment]
@morethanreal Please try again if you can see the image.

**Comment by motss** [comment]
I used it with paper-tabs. 
Steps to reproduce error:
- click on each tabs once to see if it is showing the correct content.
- click on the second tab (or Page 2) several times.
- then click on any other tab like the last tab (Page 3). The overlap will occur.

**Comment by solomongracio** [comment]
Any update on this ? I am also facing the same issue.

**Comment by hawkett** [comment]
This is probably a duplicate of #71 and #74. #75 is intended to fix this problem, but has been waiting nearly a month to merge unfortunately.

**Comment by cdata** [comment]
Closing as fixed by #75.
