### ISSUE TITLE
Reliance on paper-styles adds bloat

### ISSUE THREAD

**Issue by carlosperez** [PolymerElements/neon-animation#47]
`neon-animated-pages.html` imports `../paper-styles/paper-styles.html` which brings with it a considerable amount of assets (iron-flex-layout, Roboto font from Google Fonts, paper theming, etc.).

What's the recommended course of action to exclude this? Right now, I'm not using any page transitions at all, so I can simply remove the import of `neon-animated-pages.html` from `neon-animation.html` but that's not a good long term solution given a bower update would kill that change.

Should paper-styles even be required in the first place? Would a paper-specific version of neon-animation make sense so that neon-animation itself is as basic a component that doesn't care or make assumptions about your theming? Or, should paper require neon-animation instead?

**Comment by morethanreal** [comment]
Fixed in https://github.com/PolymerElements/neon-animation/commit/5164a110c0e8b79ebbde0efbc2af2b16316a22f7

**Comment by carlosperez** [comment]
Nice - thank you!
