### ISSUE TITLE
Impossible to configure animation after the element has been created.

### ISSUE THREAD

**Issue by kirilledelman** [PolymerElements/neon-animation#48]
I have `<paper-dialog>` element, which is statically declared on the page. I'd like to configure its entry and exit animations - and I do so in my `WebComponentsReady` event handler.

            // configure modal dialog's animations
            this.modalDialog.animationConfig = {
                value: function () {
                    return {

                        // scale up
                        'entry': {
                            name: 'scale-up-animation',
                            node: this,
                            timing: { duration: 200, easing: 'ease-out' }
                        },

                        // fade out
                        'exit': {
                            name: 'fade-out-animation',
                            node: this,
                            timing: { duration: 100 }
                        }
                    }
                }.bind( this.modalDialog )
            };

No effect. It works ( without `.bind(...)` ) part if I make my own element and configure animation in `properties {}` block, but it's awfully cumbersome to do so just for that.

Additionally, `animationConfig` value is a Function - I'd expect it to be called every time you call `.playAnimation()` to be able to modify animation parameters, if needed, based on current state of the element, but it seems the animations are pre-configured during initialization, and are not modifiable.

**Comment by morethanreal** [comment]
That syntax is only needed to configure the initial value for a property in the `properties` block. https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#configure-values

At any time before the animation is triggered you can set `animationConfig` directly, ie.
```js
this.modalDialog.animationConfig = {
  // scale up
  'entry': {
    name: 'scale-up-animation',
    node: this,
    timing: { duration: 200, easing: 'ease-out' }
  },
  // fade out
  'exit': {
    name: 'fade-out-animation',
    node: this,
    timing: { duration: 100 }
  }
};
```
