### ISSUE TITLE
why not sequenceEffect  function in neon-animation

### ISSUE THREAD

**Issue by bugknightyyp** [PolymerElements/neon-animation#50]
There are keyframeEffect and groupEffect but not sequenceEffect  in neon-animation. why?

**Comment by morethanreal** [comment]
@bugknightyyp I'm afraid I don't understand the question. Neither `keyframeEffect` and `groupEffect` are API in `neon-animation`. Can you explain what you're looking for?

**Comment by bugknightyyp** [comment]
Thanks @morethanreal. In [web animations spec](https://github.com/web-animations/web-animations-js#build-target-comparison), there are three animation constructures: KeyframeEffect, SequenceEffects and GroupEffects. when  want to run mult animations in sequence, the SequenceEffects may be the best choice.

**Comment by cdata** [comment]
@bugknightyyp These constructs come from the Web Animations polyfill. If any are missing, you should report bugs there. https://github.com/web-animations/web-animations-js
