### ISSUE TITLE
web-animations-js update breaks neon-animation.

### ISSUE THREAD

**Issue by hourliert** [PolymerElements/neon-animation#51]
Hi,

The last update (2.1.1) of web-animation-js breaks neon-animation.

How to reproduce:
* Clone `neon-animation`
* replace in `bower.json` : `"web-animations-js": "web-animations/web-animations-js#^2.0.0"` with `"web-animations-js": "web-animations/web-animations-js#2.1.1"`
* `bower update && polyserve`
* Try a demo

Thomas.

**Comment by naoak** [comment]
It seems that Safari and Firefox work all right, but Chrome does not.

**Comment by firasdib** [comment]
Same here.

**Comment by justinribeiro** [comment]
Chrome seems to be having similar issues with 2.0.0 as well for the demos; I've tested in Chrome 45 and 43.

In a cursory glance in Dev Tools (shown in the gif in Chrome 45), it appears that `neon-animating` is not being applied (but I haven't debugged it further).

![dev-tools-grab](https://cloud.githubusercontent.com/assets/643503/8485029/bc6585ce-20af-11e5-98a0-5f4ce6fb27b9.gif)

Note, this doesn't occur in Firefox (we can see `neon-animating` being applied and the animation occuring):

![dev-tools-grab-ff](https://cloud.githubusercontent.com/assets/643503/8485500/e3d1502c-20b2-11e5-8fb5-bba2606353e8.gif)

**Comment by cedric-marcone** [comment]
The only option ATM, is to force downgrade ow web-animation-js dependency in your bower.json : 
```json
"web-animations-js": "web-animations/web-animations-js#2.0.0"
```

**Comment by LM450N** [comment]
Thanks @cedric-marcone for the _workaround_.

**Comment by morethanreal** [comment]
There's a bug in the `web-animations-js` 2.1.1 release: https://github.com/web-animations/web-animations-next/issues/390

I'm pinning the verion to 2.1.0 until that is fixed.

**Comment by mikelawther** [comment]
There is a 2.1.2 release of web-animations-js which should fix this problem. Can somebody please confirm?

**Comment by morethanreal** [comment]
@mikelawther looks good to me, thanks!
