### ISSUE TITLE
google-map does not render to its size when used in core-animated-pages when it is in secion 1+

### ISSUE THREAD

**Issue by atotic** [PolymerElements/neon-animation#57]
_From @tobiashutterer on July 15, 2014 14:23_

using <google-map> in a <core-animated-pages> just works right on index=0. When i try using or styling it on index 1-x the box is as i defined it, but the redered map just shows about 200px in the left upper corner of the map box.
. 
Might this me a bug, or am I too stupid? I hope it is the second one. 

![image](https://cloud.githubusercontent.com/assets/8007595/3585946/60e0286a-0c2b-11e4-8aa7-2c1f0516a959.png)

_Copied from original issue: GoogleWebComponents/google-map#33_

**Comment by atotic** [comment]
_From @bamnet on July 15, 2014 14:38_

Can you link to a sample which reproduces this?

**Comment by atotic** [comment]
_From @ebidel on July 15, 2014 17:35_

I believe the problem is related to the fact that the map's container is `display: none` initially.  From [here](http://stackoverflow.com/a/3412601/274673), the fix is:

    google.maps.event.trigger(map, 'resize');

Haven't tested, but we can bake something like this into the map element.

**Comment by atotic** [comment]
_From @ebidel on July 16, 2014 5:42_

Unfortunately, there's no good way to detect when the parent element of the map becomes visible. I got it working by polling if `.offsetParent` was set using rAF callbacks, but that's not ideal. If core-animated-pages were to fire an event, the client can call `mapEl.resize()` to ensure the map is displayed properly. That method already has the `google.maps.event.trigger(map, 'resize');` trick.

In the general case, `mapEl.resize()` will adjust the map to display properly.

**Comment by atotic** [comment]
_From @sjmiles on July 16, 2014 6:16_

Fwiw, this is a common problem and we need to work out a way to inform downstream elements of these kind of changes. I'm reluctant to get into _broadcasting_, but I don't have any better ideas at the moment.

**Comment by atotic** [comment]
_From @addyosmani on July 16, 2014 8:38_

Are there perf implications of excessive broadcasting you're concerned of?

**Comment by atotic** [comment]
_From @ebidel on July 16, 2014 17:27_

We almost need a platform primitive to know if an element is in the render tree.

**Comment by atotic** [comment]
_From @ebidel on July 16, 2014 22:4_

`core-animated-pages` now fires the "core-animated-pages-transition-prepare" event when transitions occur: https://github.com/Polymer/core-animated-pages/commit/e18d5bfb9c90ee903ec62fc6e9f89438f7553787

This should do the trick:

    animatedPagesEl.addEventListener('core-animated-pages-transition-prepare', function() {
      mapsEl.resize();
    });

**Comment by atotic** [comment]
_From @ebidel on July 30, 2014 21:9_

@tobiashutterer we moved this to the GoogleWebComponents org and will be keeping the release version up to date more frequently. You'll get the latest when using the plain `bower install GoogleWebComponents/google-map`.

Closing this as the workaround is posted above for the original issue.

**Comment by atotic** [comment]
_From @phidias51 on March 10, 2015 20:6_

I've noticed the same problem when embedding the map in a core-pages element or a core-collapse element.  It looks like the map is being translated up and to the left, leaving grey space behind in its wake.  The position is not centered in the middle of the map.  Also, the map.resize() call is causing the original lat/longs to be shifted.

**Comment by atotic** [comment]
_From @Zippersk on June 15, 2015 15:12_

I have same problem with neon-animated-pages. I can't find som fire like neon-animated-pages-transition-prepare. Is there any solution to display map?

**Comment by atotic** [comment]
Pull #152 should have fixed this for neon-animated-pages. Have you tried #master

**Comment by atotic** [comment]
_From @Zippersk on June 15, 2015 17:5_

Install master verison helps! Thaks a lot. :)

**Comment by atotic** [comment]
_From @kingflurkel on July 9, 2015 15:38_

I still have this bug with neon-animated-pages. 
I use this version:     "google-map": "GoogleWebComponents/google-map#^1.0.0",
Any help / tips to get this working?

**Comment by atotic** [comment]
@kingflurkel if you have a test case, I can take a look

**Comment by atotic** [comment]
_From @kingflurkel on July 9, 2015 18:8_

http://actaanbod.bitballoon.com/
Click on the location icon. So I have google-map within iron-animated-pages.
Code: 
https://github.com/A-StadLabs/activiteitenaanbod/tree/master/app/elements/a-activiteitenstage
https://github.com/A-StadLabs/activiteitenaanbod/blob/master/app/elements/a-locatie/a-locatie.html

**Comment by atotic** [comment]
Thanks.
google-map is not getting the iron-resize event. I'll have to dig in to
find out why.

**Comment by atotic** [comment]
_From @kingflurkel on July 9, 2015 18:31_

Maybe because google-map is in another custom-element, which is in iron-pages?

**Comment by atotic** [comment]
The problem is in the neon-animated-pages. Because map is inside a custom element, it does not get a notification that it has been shown.  Iniside neon-animated-pages:

```
      this.resizerShouldNotify = function(element) {
        return element == selectedPage;
      }
      this.notifyResize();
```

This should probably be: if element is selectedPage, or its parent is a selected page.

**Comment by naoak** [comment]
Hmm.. It certainly has a problem. For the present, adding IronResizableBehavior to pages (in this case, a-locatile) might be work.

**Comment by naoak** [comment]
This resizerShouldNotify trick code restricts resize notifications to only a selected page so that unnecessary resize notifications to invisible pages can be removed. But it requires children pages to be iron-resizable. I think we can handle this issue by two ways.

1. Improve the trick to check if an element's ancestor is a selected page.

2. Remove the trick and handle iron-resize events in each pages on user responsibility so that invisible pages ignore resize notifications.

Do you think which is the better?

**Comment by naoak** [comment]
I made a PR with the 1st way. Please confirm it.

**Comment by atotic** [comment]
Thanks, we'll have to wait for animated-pages owner to take a look at it.

**Comment by kingflurkel** [comment]
Yes @naoak ! This works like a charm.

**Comment by naoak** [comment]
Sorry to cause you trouble...
But, that's good to hear:)

**Comment by morethanreal** [comment]
@naoak I think your suggestion 2 is the better fix, because we decide whether or not to fire `iron-resize` on a subtree is at the page level. Since the interested node could be n levels deep it seems better to not walk the tree every time resize is fired.

**Comment by naoak** [comment]
You're absolutely right. The 1st way has a performance issue that cannot be ignored. I also think the 2nd is the better. But, on neon-animated-pages, it is a common case that invisible pages receive `iron-resize` events which originally should be ignored. I'd like to know a standard manner how to achieve this.
Many thanks.

**Comment by morethanreal** [comment]
@naoak @atotic `IronResizableBehavior` intends for both the resizing and resized element to implement the behavior, but in the case of `neon-animated-pages` it is resizing an element it doesn't own (ie. not itself, and not in its local DOM). My first thought is to require the user to implement `IronResizableBehavior`, but I echo the concerns about making this easy to use. I added some comments in the PR.

**Comment by naoak** [comment]
OK, I see. I found `iron-pages` also has the redundant resize notification issue, seeing  https://github.com/PolymerElements/iron-pages/blob/master/iron-pages.html#L91. 
I think reverting `neon-animated-pages`'s notification is good to follow it, for the time being.

**Comment by morethanreal** [comment]
@naoak How do you feel about moving your PR to `iron-pages`?

**Comment by naoak** [comment]
@morethanreal I am okay with that. This issue is not essentially related with animations.

**Comment by cdata** [comment]
Moving this to `iron-pages`.

**Comment by cdata** [comment]
This issue was moved to PolymerElements/iron-pages#22
