### ISSUE TITLE
Issue with resizerShouldNotify

### ISSUE THREAD

**Issue by blasten** [PolymerElements/neon-animation#60]
from: https://github.com/PolymerElements/paper-scroll-header-panel/issues/33#issuecomment-123113078

check:
https://github.com/PolymerElements/neon-animation/blob/00396d460a137add49a744ab21ba337cd989238c/neon-animated-pages.html#L212-L217

`selectedPage` is a neon-animatable,  but `element` is the paper-scroll-header-panel

**Comment by ronnyroeller** [comment]
+1

**Comment by mgiuffrida** [comment]
+1, need PolymerElements/iron-list#54 fixed for Chrome Settings.

**Comment by WilliamSWoodruff** [comment]
+1

**Comment by bpinney** [comment]
+1

**Comment by Compufreak345** [comment]
Any progress on here?

**Comment by motss** [comment]
Any workaround for [PolymerElements/iron-list#54](https://github.com/PolymerElements/iron-list/issues/54) and [PolymerElements/iron-list#110](https://github.com/PolymerElements/iron-list/issues/110)?

**Comment by mgiuffrida** [comment]
@motss: Try firing `iron-resize` on the `iron-list` at the point when the `neon-animatable` should be shown.

**Comment by motss** [comment]
@mgiuffrida Thank you! Tried and it worked! :clap:

**Comment by Compufreak345** [comment]
@mgiuffrida Your workaround also works for me.

@blasten: Can you tell any estimated time of implementation? It is not the first time I fall over this tripwire and am wondering why my updated list does not refresh after changing back from the edit-page. 

For now I am using this (a bit hacky) code : 

    <neon-animated-pages on-neon-animation-finish="_onPageChange">
         [...]
    </neon-animated-pages>

    _onPageChange:function(e,a) {
            Polymer.dom(a.toPage).querySelectorAll('iron-list').forEach(function (list) {
                list.fire("iron-resize");
            });
        }

It kind of works, but as I don't see an neon-animation-start-event it refreshes the list after the transition :/ (Calling the iron-resize before the page change starts also does not seem to work, changed list items are not refreshed if I don't put a delay in the call).

**Comment by blasten** [comment]
@Compufreak345 We will be looking at this issue soon. cc @valdrinkoshi

**Comment by ziszo** [comment]
< neon-animated-pages >
         < paper-dialog >

Dialog closes after a few seconds.
Is there any work-around for this?

**Comment by ziszo** [comment]
< neon-animated-pages >
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;< paper-dialog >

Dialog closes after a few seconds.
Is there any work-around for this issue like PolymerElements/iron-list#110

**Comment by valdrinkoshi** [comment]
@ziszo is there a particular reason you put the `paper-dialog` inside `neon-animated-pages` ?
`paper-dialog` extends `paper-dialog-behavior`, which extends `iron-overlay-behavior`. As per [documentation](https://elements.polymer-project.org/elements/iron-overlay-behavior)
> You should place this element as a child of <body> whenever possible.
