### ISSUE TITLE
Animations shouldn't set properties in the configure method

### ISSUE THREAD

**Issue by myfreeweb** [PolymerElements/neon-animation#61]
For example, `hero-animation` does this in the `configure` method:
```js
shared.from.style.visibility = 'hidden';
```

Because of this, delaying the `hero-animation` looks like a total disaster: the hero element is hidden before the `hero-animation` starts.

**Comment by cdata** [comment]
This sounds like a problem that is specific to `hero-animation`. Could you provide a reduced test case that demonstrates the issue and re-open? Thanks!
