### ISSUE TITLE
Resize ignored because this.selectedItem is undefined.

### ISSUE THREAD

**Issue by hourliert** [PolymerElements/neon-animation#62]
Hi.

I wonder why in this [file](https://github.com/PolymerElements/neon-animation/blob/ec51bf68f05c40373536cc726ca674e4549b7db2/neon-animated-pages.html#L215), the selectedPage is stored in a variable and used rather than be used directly in the callback.

I mean could this:

```javascript
var selectedPage = this.selectedItem;
this.resizerShouldNotify = function(element) {
  return element == selectedPage;
}
```

be this:

```javascript
this.resizerShouldNotify = function(element) {
  return element == this.selectedItem;
}
```

I've got an issue with this. I need to resize a child component of the selected page. When the previously callback is called, `selectedItem` is unknow. It could occured if the method `_notifyPageResize` is called before this [method](https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html#L215).

**Comment by cdata** [comment]
This is a weird implementation. Thanks for pointing it out!
