### ISSUE TITLE
hero-id?

### ISSUE THREAD

**Issue by g-ortuno** [PolymerElements/neon-animation#65]
On the grid demo page the `fullsize-page-with-card` element has `hero-id="hero"` but there is no documentation on what `hero-id` is or why it is needed.

**Comment by Jonasei** [comment]
This is explained in the latest Polycast video: https://www.youtube.com/watch?v=wMhq1o0DULM

**Comment by g-ortuno** [comment]
Thanks for the video. It doesn't mention `hero-id` though. It seems like something that was left over from Polymer 0.5.

**Comment by cdata** [comment]
@g-ortuno @Jonasei I think this is vestigial. We should remove it. Thanks for reporting!
