### ISSUE TITLE
Fade-in-animation has a flicker issue

### ISSUE THREAD

**Issue by bflora2** [PolymerElements/neon-animation#66]
I am seeing a flicker problem for dialogs using the fade-in-animation: When dialog.open() is called the dialog appears instantly, disappears after maybe 100mS, then fades in normally.

The problem is sporadic, and occurs on Firefox, IE, and Edge, but never on Chrome (perhaps indicating a race condition in the polyfill code?). The problem occurs most frequently on IE 11 and Edge.

For now, I have replaced the fade-in-animation with the scale-up-animation which does not appear to exhibit the problem.

**Comment by bflora2** [comment]
Workaround until fix is available:
Set the dialog's opacity style to zero just before calling open(). Ensure "opened" is false before zeroing the opacity, otherwise you will introduce a flicker on the dialog's dismissal if it is already displayed and it uses the fade-out-animation.

**Comment by ronnyroeller** [comment]
+1

**Comment by cdata** [comment]
Can you provide a reduced test case and re-open? Thanks!
