### ISSUE TITLE
TypeError: this.unlisten is not a function at neon-animated-pages... With Iron-Dropdown

### ISSUE THREAD

**Issue by zmoshansky** [PolymerElements/neon-animation#69]
Chrome throws the following error when refreshing on a page with `<iron-dropdown>` inside `<neon-animated-pages>`. Everything is fine if I load a different page and then navigate to the same page (SPA). I'm not sure if it's some sort of bug related to a race condition, or my own implementation fault. (My apologies if this should have been reported in the `iron-resizable` repo)

##### Error
`TypeError: this.unlisten is not a function at neon-animated-pages.Polymer.IronResizableBehavior.stopResizeNotificationsFor (.../iron-resizable-behavior/iron-resizable-behavior.html:119:14) at iron-dropdown.Polymer.IronResizableBehavior.detached (.../iron-resizable-behavior/iron-resizable-behavior.html:76:31) at iron-dropdown.Polymer.Base._addFeature._invokeBehavior (.../polymer/polymer-micro.html:283:4) at iron-dropdown.<anonymous> (.../polymer/polymer-micro.html:276:6) at Array.forEach (native) at iron-dropdown.Polymer.Base._addFeature._doBehavior (.../polymer/polymer-micro.html:275:16) at iron-dropdown.Polymer.Base.detachedCallback (.../polymer/polymer-micro.html:117:6) at Object.Polymer.DomApi.DomApi.appendChild (.../polymer/polymer-mini.html:441:19) at dom-repeat.Polymer._detachRow (.../polymer/polymer.html:3429:23) at dom-repeat.Polymer._render (.../polymer/polymer.html:3303:6)`

##### Relevant function causing the error
```
    stopResizeNotificationsFor: function(target) {
      var index = this._interestedResizables.indexOf(target);

      if (index > -1) {
        this._interestedResizables.splice(index, 1);
        this.unlisten(target, 'iron-resize', '_onDescendantIronResize');
      }
    },
```
##### Variables
`this` = `neon-animated-pages#main-pages-container.fit.style-scope` 
`target` = `iron-dropdown#dropdown.style-scope.paper-menu-button`

**Comment by cdata** [comment]
Hi, thanks for reporting. Can you provide a reduced test case and re-open?

Here are the guidelines for filing issues, if it helps: https://github.com/PolymerElements/neon-animation/blob/master/CONTRIBUTING.md#filing-issues
