### ISSUE TITLE
Rapidly changing pages can lose track of 'neon-animating' class

### ISSUE THREAD

**Issue by atotic** [PolymerElements/neon-animation#74]
If you rapidly switch between multiple pages, 'neon-animating' flag can get stuck on one of your pages. This causes the entire page to be unclickable.

The cause is that previous animation gets cancelled before it even starts, so _squelchNextFinishEvent flag does not get cleared by _neonAnimationFinish.

I have a simple fix, filing this to have a bug to reference.

**Comment by johnheroy** [comment]
+1, also seeing this issue.

**Comment by hawkett** [comment]
Is this a duplicate of #71?
