### ISSUE TITLE
No equivalent of 'core-animated-pages-transition-prepare'

### ISSUE THREAD

**Issue by David-Mulder** [PolymerElements/neon-animation#76]
> What's the equivalent of `core-animated-pages-transition-prepare` in `<neon-animated-pages>`?

> Specifically I need to trigger `measureHeaderHeight` on my `<paper-scroll-header-panel>` before it's actually shown, but after it is 'visible' in the DOM. 

Per: http://stackoverflow.com/questions/32555991/whats-the-equivalent-of-core-animated-pages-transition-prepare-in-neon-anima it seems to be the case the event is missing in the new `<neon-animation>`-element.

**Comment by cdata** [comment]
Hi, could you re-open this issue with a design proposal for the feature?

For more details and suggestions, please refer to our [contribution guidelines](../blob/master/CONTRIBUTING.md)!
