### ISSUE TITLE
transform translateY not working in firefox, edge browsers with animation

### ISSUE THREAD

**Issue by suneelv** [PolymerElements/neon-animation#80]
Hi, I am doing animation on transform property. Everything works fine in chrome, but when I test the same in firefox or edge its not working.

this is my animation 

        {'transform': transformFrom},
        {'transform': transformTo},

transformFrom = transform: translateY(77px) scale(0.941667);
transformTo = transform: translateY(70px) scale(0.911667); 

and on neonAnimationFinish, I am setting the new transform property to the element. This works fine in chrome but not in any other browser.

If I remove the animation and set the property normally, then its working in other browsers too. I checked the element in browser console and transform property is not attached to it after animation.

Is that a bug in neon animation?

**Comment by mbergeron** [comment]
I do have the same problem with slide-up animation.

After the neonAnimationFinish event, I set my element transform property for it to stay in place but the transform property is not kept in Safari and Firefox. All is fine in Chrome.

It's almost like something happen after the neonAnimationFinish that resets the property.

**Comment by cdata** [comment]
Hi, could you please re-open this issue with a reduced test case? Otherwise, we cannot determine if it is a bug in `neon-animation` or the Web Animations polyfill.

Here are our contributor guidelines for filing issues, if it helps: https://github.com/PolymerElements/neon-animation/blob/master/CONTRIBUTING.md#filing-issues
