### ISSUE TITLE
bug in NeonAnimationRunnerBehavior

### ISSUE THREAD

**Issue by fooloomanzii** [PolymerElements/neon-animation#83]
I made an element with a NeonAnimationRunnerBehavior and configure it with a timing like this:

```javascript
animationConfig: {
        value: function() {
          return {
            'entry': [
              {
                name: 'fade-in-animation',
                node: this.$.insideElement,
                timing: {
                  duration: 1000,
                  iterations: 3,
                  direction: "alternate",
                } }
            ] } } },
```

and called in an element with a NeonSharedElementAnimatableBehavior and configured that like:

```javascript
        animationConfig: {
          value: function() {
            return {
              'entry': [
                {animatable: this.$.myElement, type: 'entry'}
              ] } } },
```
 
to call it in an neon-animated-pages, when the page change.
Generally it animates and it works. The Problem is, that the webanimation doesn't switch then to the finished state in
```javascript
        this._player.onfinish = function() {
          this._completeAnimations(allAnimations);

          if (this._player) {
            this._player.cancel();
            this._player = null;
          }

          this.fire('neon-animation-finish', cookie, {bubbles: false});
        }.bind(this);
```
And therefore the page turn doesn't finish and it is not accessible for events (like clicks). If you don't configure it with an *iteration*, the finish-event would be fired. You can work around by firing **neon-animation-finish** yourself, but this is a bug

**Comment by fooloomanzii** [comment]
I made a example, showing this bug
http://jsbin.com/wanebecole/1/edit?html,console,output

**Comment by cdata** [comment]
@fooloomanzii this test case is showing an exception for me, and does not appear to work. Could you please update the test case and re-open the issue? Thanks!

**Comment by fooloomanzii** [comment]
@cdata Actually neon-animation now has an extra bug. The **animate-initial-selection** attribute doesn't work and that's what you see in the console output.

`<neon-animated-pages id="pages" animate-initial-selection selected="">`

But the reason for that might be related to *iron-selector*. So if you deselect that attibute, it would run, but then my initial question is obsolete, because it's related to entry-animations.
http://jsbin.com/gudedo/edit?html,console,output

This should actually be a new issue.
