### ISSUE TITLE
Neon-animated-pages does not resize to its content

### ISSUE THREAD

**Issue by maxiplay** [PolymerElements/neon-animation#84]
http://stackoverflow.com/questions/31569813/neon-animated-pages-does-not-resize

My solution 

https://github.com/maxiplay/neon-animation

**Comment by cdata** [comment]
Hi, could you re-open this issue according to our contributor guidelines? Thanks.

https://github.com/PolymerElements/neon-animation/blob/master/CONTRIBUTING.md#filing-issues
