### ISSUE TITLE
Can neon-animated-pages  used inside any other element?

### ISSUE THREAD

**Issue by nagababji123** [PolymerElements/neon-animation#94]
Hai,

I have written neon-animated-pages inside the paper-card or div its not displaying the background color.
Can neon-animated-pages be used inside any other elements or not?

its just showing white background and displaying content, but when I am using without paper-card or divs its displaying background color.
#AskPolymer
Any help is appreciated,
Thank you,
Babji.

**Comment by cdata** [comment]
Hi, please re-open with a reduced test case. Thanks!
