### ISSUE TITLE
Use multiple shared elements?

### ISSUE THREAD

**Issue by BartKoppelmans** [PolymerElements/neon-animation#97]
Hello,

Is it possible to use multiple heroes in a hero animation? I would like to animate a card and a child to a bigger card and move the child. Would this be possible to do and how would I tackle this problem?

Bart

**Comment by dsschnau** [comment]
Hey Bart,
 Yes you can have multiple `hero`s. You give each `hero` an id in the `fromPage` and `toPage` `sharedElements` property and the hero-animation should take it from there.

Sorry I can't write up a bigger explanation at the moment but post again if you have a question or need more help.

**Comment by BartKoppelmans** [comment]
Anybody an idea how to do this in the following example:
``` Javascript
Polymer({
    is: 'paper-letter-detail-page',
    behaviors: [
      Polymer.NeonSharedElementAnimatableBehavior
    ],
    properties: {
      sharedElements: {
        value: function() {
          return {
            'hero-date': this.$.date,
            'hero-paper': this.$.paper
          }
        }
      },
      animationConfig: {
        value: function() {
          return {
            'entry': {
              name: 'hero-animation',
              id: ['hero-date', 'hero-paper'],
              toPage: this
            }
          };
        }
      }
    }
  });
```
